%% eb3dprefs
function pr=eb3dprefs(action)

if nargin==0,action='initialize';end

f_size=11;
BGCOL=[0.75 0.75 0.75];

g=grapconsts;

cfig=findwind('Eye Monitor Control');
if ~ishandle(cfig)
   disp('Eye Monitor Control window is missing!')
   return
end
ch=cfig.UserData;
pr=ch.eb3dPrefsBH.UserData;

efig=findwind('Eye Monitor');
if ~ishandle(efig)
   disp('Eye Monitor window is missing!')
   return
end
eh=efig.UserData;

pfig=findwind('Preferences');
if ishandle(pfig) && strcmpi(action,'initialize')
   figure(pfig)
   return
end

if strcmpi(action,'initialize')
   parent_w_pos=cfig.Position;
   mfig_ht=375;
   fig_wid=280;
   pfig=figure('Resize','off','Menubar','None', ...
      'Position',[parent_w_pos(1)+180 parent_w_pos(2)-70 fig_wid mfig_ht],...
      'Name','Preferences','NumberTitle','off');
   
   
   
   %%  create the controls
   x0=10;
   ypos=mfig_ht;
   
   ypos=ypos-60;
   uicontrol(pfig,'Style','frame','Units','pixels',...
      'HorizontalAlignment','Left',...
      'BackgroundColor',BGCOL,'Position',[3 ypos 276 58]);
   ypos=ypos+30;
   uicontrol('Style','text','BackgroundColor',BGCOL,...
      'Position',[x0 ypos+3 40 20],'String','ID string');
   pr.idStrH = uicontrol('Style','edit',...
      'Position',[x0+65 ypos+4 200 20],'UserData',0,...
      'BackgroundColor','c','ForegroundColor','k',...
      'String',eh.btxt.String,'Fontsize',f_size,...
      'Tooltip','Add ID text to the upper left corner of your movie',...
      'Callback',@(src,eventdata) ebAct3D('set_idstr'));
   
   % color and font size
   ypos=ypos-25;
   a=whatcolor(pr.btxtcolor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','Left',...
      'Position',[x0 ypos 60 20],'String','ID text color');
   pr.idColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+65 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'UserData',[],...
      'Callback',@(src,eventdata) ebAct3D('idtxtcolor'));
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0+185 ypos 20 20],'String','Size');   
   pr.idSizeH = uicontrol('Style','edit','Units','pixels',...
      'Position',[x0+210 ypos 40 20],...
      'BackgroundColor','c','ForegroundColor','k',...
      'String',num2str(eh.btxt.FontSize),'HorizontalAlignment','center',...
      'Tooltip','ID text size','Enable','on',...
      'Callback',@(src,eventdata) ebAct3D('idtxtsize'));
   
   
   %%%
   ypos=ypos-65;
   uicontrol(pfig,'Style','frame','Units','pixels',...
      'BackgroundColor',BGCOL,'Position',[3 ypos+3 276 54]);
   ypos=ypos+35;
   ypos=ypos-2;
   uicontrol('Style','text','BackgroundColor',BGCOL,...
      'Position',[x0 ypos 40 20],'String','Format');
   pr.movieFormatH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+65 ypos-5 90 25],...
      'String','MPEG-4|AVI','Tooltip','Choose the codec',...
      'Enable','on','Value',pr.movieformat,...
      'HorizontalAlignment','center','Callback',[]);
   
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0+165 ypos 40 20],'String','Quality');
   pr.movieQualH = uicontrol('Style','edit','Units','pixels',...
      'Position',[x0+210 ypos 40 20],...
      'BackgroundColor','c','ForegroundColor','k',...
      'String',num2str(pr.moviequality),'HorizontalAlignment','center',...
      'Tooltip','Set the movie quality',...
      'Enable','on','Callback',[]);
   
   ypos=ypos-25;
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','left',...
      'Position',[x0 ypos 70 20],'String','Movie Speed');
   pr.moviespeedH = uicontrol('Style','edit',...
      'Position',[x0+75 ypos 40 20],...
      'BackGroundColor','c','ForeGroundColor','k',...
      'Tooltip','Movie duration will be ''x'' times real-time',...
      'String',num2str(pr.movie_speed),'Callback',[] );
   
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'Position',[x0+175 ypos 30 20],'String','FPS');
   pr.fpsH = uicontrol('Style','edit',...
      'Position',[x0+210 ypos 40 20],...
      'BackGroundColor','c','ForeGroundColor','k',...
      'Tooltip','Speed (frames/sec) of the movie',...
      'String',num2str(pr.movie_fps),'Callback',[] );
   %'String',num2str((samp_freq/playstep)*pr.movie_speed),'Callback',[] );
   
   
   %%% Eye and Line Colors
   plotHOR = ch.plotHORh.Enable;
   plotVRT = ch.plotVRTh.Enable;
   plotTOR = ch.plotTORh.Enable;
   plotSTM = ch.plotSTMh.Enable;
   %plotXY  = ch.plotXYh.Enable;

   ypos=ypos-178;
   uicontrol(pfig,'Style','frame','Units','pixels',...
      'BackgroundColor',BGCOL,'Position',[3 ypos 276 170]);
   
   ypos=ypos+145;
   a=whatcolor(pr.eyeColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0 ypos 20 20],'String','Iris');
   pr.eyeColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+20 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'UserData',[],...
      'Callback',@(src,eventdata) ebAct3D('eyecolor'));
   
   % horizontal
   ypos=ypos-30;
   a=whatcolor(pr.rhColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0 ypos 20 20],'String','RH');
   pr.rhColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+20 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','rh','UserData',[1,1],...
      'Enable',plotHOR,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));
   a=whatcolor(pr.lhColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0+135 ypos 20 20],'String','LH');
   pr.lhColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+155 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','lh','UserData',[1,2],...
      'Enable',plotHOR,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));

   
   % vertical
   ypos=ypos-25;
   a=whatcolor(pr.rvColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0 ypos 20 20],'String','RV');
   pr.rvColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+20 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','rv','UserData',[2,1],...
      'Enable',plotVRT,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));
   a=whatcolor(pr.lvColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0+135 ypos 20 20],'String','LV');
   pr.lvColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+155 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','lv','UserData',[2,2],...
      'Enable',plotVRT,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));
   
   
   % torsional
   ypos=ypos-25;
   a=whatcolor(pr.rtColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0 ypos 20 20],'String','RT');
   pr.rtColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+20 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','rt','UserData',[3,1],...
      'Enable',plotTOR,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));
   a=whatcolor(pr.ltColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0+135 ypos 20 20],'String','LT');
   pr.ltColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+155 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','lt','UserData',[3,2],...
      'Enable',plotTOR,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));
   
   
   % stimuli
   ypos=ypos-30;
   a=whatcolor(pr.stColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0 ypos 20 20],'String','ST');
   pr.stColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+20 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','st','UserData',[4,1],...
      'Enable',plotSTM,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));
   a=whatcolor(pr.svColor);
   uicontrol('Style','text','BackGroundColor',BGCOL,...
      'HorizontalAlignment','right',...
      'Position',[x0+135 ypos 20 20],'String','SV');
   pr.svColorH = uicontrol('Style','popup','Units','pixels',...
      'Position',[x0+155 ypos 112 20],...
      'String',a.colorlist(1:g.LASTCOLOR+1),'FontSize',f_size, ...
      'Value',a.index,'Tag','sv','UserData',[4,2],...
      'Enable',plotSTM,...
      'Callback',@(src,eventdata) ebAct3D('lincolor'));
   
   ypos=ypos-30;
   pr.wfigBGH = uicontrol('Style','checkbox',...
      'Position',[x0 ypos 250 20],'Fontsize',f_size,...
      'BackgroundColor',BGCOL,...
      'String','Use black background for waveform window',...
      'Tooltip','Light or dark waveform background',...
      'Visible','on','Value',0,'UserData',[], ...
      'Callback',@(src,eventdata) ebAct3D('change_bg'));
      
   
   %%%%%%%%
   pr.defaultBH = uicontrol(pfig,'Style','Pushbutton',...
      'Position',[x0 5 50 20],'UserData',0,...
      'Tooltip','Restore prefs to default values','String','Defaults',...
      'Callback',@(src,eventdata) eb3dprefs('defaults'));
   
   pr.doneBH = uicontrol(pfig,'Style','Pushbutton',...
      'Position',[220 5 50 20],'UserData',0,...
      'Tooltip','Close this window','String','Done',...
      'Callback','close(''gcf'')');


elseif strcmpi(action,'refresh_pr')
   pr.movieformat  = pr.movieFormatH.Value;
   pr.moviequality = str2double(pr.movieQualH.String);
   pr.movie_fps    = str2double(pr.fpsH.String);
   pr.movie_speed  = str2double(pr.moviespeedH.String);
   
   pr.wfigBG=pr.wfigBGH.Value;
   
   temp=whatcolor(pr.eyeColorH.Value);  pr.eyeColor=temp.rgb;
   temp=whatcolor(pr.rhColorH.Value);   pr.rhColor=temp.rgb;
   temp=whatcolor(pr.rvColorH.Value);   pr.rvColor=temp.rgb;
   temp=whatcolor(pr.lhColorH.Value);   pr.lhColor=temp.rgb;
   temp=whatcolor(pr.lvColorH.Value);   pr.lvColor=temp.rgb;
   temp=whatcolor(pr.stColorH.Value);   pr.stColor=temp.rgb;
   temp=whatcolor(pr.svColorH.Value);   pr.svColor=temp.rgb;
   
   pr.btxtstr=pr.idStrH.String;
   pr.btxtsize=str2double(pr.idSizeH.String);
   temp=whatcolor(pr.idColorH.Value);  
   pr.txtxcolor=temp.rgb;
   
   ch.eb3dPrefsBH.UserData=pr;
   cfig.UserData=ch;

   
elseif strcmpi(action,'defaults')
   pr.btxtstr   = 'add custom text';
   pr.btxtsize  = 10;
   pr.btxtcolor = [0 0 1];
   
   pr.movieformat  = 1;  % 1=MPEG4, 2=AVI
   pr.moviequality = 0.75;
   pr.movie_fps    = 30;
   pr.movie_speed  = 1;
   
   pr.wfigBG   = 0; % 0=g.rgb{g.OFFWHITE}. 1=black;
   pr.eyeColor = g.rgb{g.CORNFLOWER};
   
   pr.rhColor = [0 0 1];
   pr.rvColor = [0 0 1];
   pr.rtColor = [0 0 1];
   pr.lhColor = [0 1 0];
   pr.lvColor = [0 1 0];
   pr.ltColor = [0 1 0];
   pr.stColor = [1 0 0];
   pr.svColor = [1 0 0];
   
   ch.eb3dPrefsBH.UserData=pr;
   cfig.UserData=ch;
   eb3dprefs('updatecontrols');
   
   
elseif strcmpi(action,'updatecontrols')
   pr.idStrH.String  = pr.btxtstr;
   pr.idSizeH.String = num2str(pr.btxtsize);
   temp=whatcolor(pr.btxtcolor); pr.idColorH.Value=temp.index;
   
   pr.movieFormatH.Value = pr.movieformat;
   pr.movieQualH.String  = num2str(pr.moviequality);
   pr.fpsH.String        = num2str(pr.movie_fps);
   pr.moviespeedH.String = num2str(pr.movie_speed);

   temp=whatcolor(pr.eyeColor);
   pr.eyeColorH.Value=temp.index;
   ebAct3D('eyecolor');
   
   temp=whatcolor(pr.rhColor);
   pr.rhColorH.Value=temp.index;
   ebAct3D('lincolor');
   
   temp=whatcolor(pr.rvColor);
   pr.rvColorH.Value=temp.index;
   ebAct3D('lincolor');
   
   temp=whatcolor(pr.lhColor);
   pr.lhColorH.Value=temp.index;
   ebAct3D('lincolor');
   
   temp=whatcolor(pr.lvColor);
   pr.lvColorH.Value=temp.index;
   ebAct3D('lincolor');
   
   temp=whatcolor(pr.stColor);
   pr.stColorH.Value=temp.index;
   ebAct3D('lincolor');
   
   temp=whatcolor(pr.svColor);pr.svColorH.Value=temp.index;
   ebAct3D('lincolor');
   
   pr.wfigBGH.Value=pr.wfigBG;      
   
end

end %function eb3dprefs


